name: Trigger workflow

on:
  push:
    paths:
      - "public.json"

run: |
  curl -XPOST -u "${{ secrets.GIT_CREDENTIALS }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/tchesa/cross-repo-action-trigger/actions/workflows/build.yml/dispatches --data '{"ref": "main" }'
