name: Trigger workflow

on:
  push:
    paths:
      - "petstore.yaml"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: convictional/trigger-workflow-and-wait
        with:
          owner: tchesa
          repo: cross-repo-action-trigger
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: build.yml
          ref: master
          wait_workflow: false
